<!DOCTYPE html>
<html>
<head>
  <title>README.md</title>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <link rel="stylesheet" media="all" href="../../doc-style.css" />
  <script src="../../doc-filelist.js"></script>
  <script>
    var relativeDir = "../../";
    var thisFile = "node_modules\\verror\\README.md";
    var defaultSidebar = true;
  </script>
  <script src="../../doc-script.js"></script>

</head>
<body>
  <div id="sidebar_wrapper">
    <div id="sidebar_switch">
      <span class="tree">Files</span>
      <span class="headings">Headings</span>
    </div>
    <div id="tree"></div>
    <div id="headings">

      <div class="heading h1">
        <a href="#verror-rich-javascript-errors">verror: rich JavaScript errors</a>
      </div>

      <div class="heading h1">
        <a href="#quick-start">Quick start</a>
      </div>

      <div class="heading h1">
        <a href="#deeper-dive">Deeper dive</a>
      </div>

      <div class="heading h1">
        <a href="#reference-verror-werror-serror">Reference: VError, WError, SError</a>
      </div>

      <div class="heading h2">
        <a href="#constructors">Constructors</a>
      </div>

      <div class="heading h2">
        <a href="#public-properties">Public properties</a>
      </div>

      <div class="heading h2">
        <a href="#class-methods">Class methods</a>
      </div>

      <div class="heading h3">
        <a href="#verror.cause-err">VError.cause(err)</a>
      </div>

      <div class="heading h3">
        <a href="#verror.info-err">VError.info(err)</a>
      </div>

      <div class="heading h3">
        <a href="#verror.fullstack-err">VError.fullStack(err)</a>
      </div>

      <div class="heading h3">
        <a href="#verror.findcausebyname-err-name">VError.findCauseByName(err, name)</a>
      </div>

      <div class="heading h3">
        <a href="#verror.hascausewithname-err-name">VError.hasCauseWithName(err, name)</a>
      </div>

      <div class="heading h3">
        <a href="#verror.errorfromlist-errors">VError.errorFromList(errors)</a>
      </div>

      <div class="heading h3">
        <a href="#verror.errorforeach-err-func">VError.errorForEach(err, func)</a>
      </div>

      <div class="heading h2">
        <a href="#examples">Examples</a>
      </div>

      <div class="heading h1">
        <a href="#reference-multierror">Reference: MultiError</a>
      </div>

      <div class="heading h2">
        <a href="#public-methods">Public methods</a>
      </div>

      <div class="heading h3">
        <a href="#errors">errors()</a>
      </div>

      <div class="heading h1">
        <a href="#contributing">Contributing</a>
      </div>

    </div>
  </div>
  <div id="sidebar-toggle"></div>
  <div id="container">
    <div class="docs markdown"><div class="pilwrap" id="verror-rich-javascript-errors">
  <h1>
    <a href="#verror-rich-javascript-errors" name="verror-rich-javascript-errors" class="pilcrow"></a>
verror: rich JavaScript errors
  </h1>
</div>
<p>This module provides several classes in support of Joyent's <a href="http://www.joyent.com/developers/node/design/errors">Best Practices for
Error Handling in Node.js</a>.
If you find any of the behavior here confusing or surprising, check out that
document first.</p>
<p>The error classes here support:</p>
<ul>
<li>printf-style arguments for the message</li>
<li>chains of causes</li>
<li>properties to provide extra information about the error</li>
<li>creating your own subclasses that support all of these</li>
</ul>
<p>The classes here are:</p>
<ul>
<li><strong>VError</strong>, for chaining errors while preserving each one's error message.
This is useful in servers and command-line utilities when you want to
propagate an error up a call stack, but allow various levels to add their own
context.  See examples below.</li>
<li><strong>WError</strong>, for wrapping errors while hiding the lower-level messages from the
top-level error.  This is useful for API endpoints where you don't want to
expose internal error messages, but you still want to preserve the error chain
for logging and debugging.</li>
<li><strong>SError</strong>, which is just like VError but interprets printf-style arguments
more strictly.</li>
<li><strong>MultiError</strong>, which is just an Error that encapsulates one or more other
errors.  (This is used for parallel operations that return several errors.)</li>
</ul>
<div class="pilwrap" id="quick-start">
  <h1>
    <a href="#quick-start" name="quick-start" class="pilcrow"></a>
Quick start
  </h1>
</div>
<p>First, install the package:</p>
<pre><code>npm install verror
</code></pre>
<p>If nothing else, you can use VError as a drop-in replacement for the built-in
JavaScript Error class, with the addition of printf-style messages:</p>
<pre><code class="javascript"><span class="hljs-keyword">var</span> err = <span class="hljs-keyword">new</span> VError(<span class="hljs-string">'missing file: "%s"'</span>, <span class="hljs-string">'/etc/passwd'</span>);
<span class="hljs-built_in">console</span>.log(err.message);
</code></pre>
<p>This prints:</p>
<pre><code>missing file: &quot;/etc/passwd&quot;
</code></pre>
<p>You can also pass a <code>cause</code> argument, which is any other Error object:</p>
<pre><code class="javascript"><span class="hljs-keyword">var</span> fs = <span class="hljs-built_in">require</span>(<span class="hljs-string">'fs'</span>);
<span class="hljs-keyword">var</span> filename = <span class="hljs-string">'/nonexistent'</span>;
fs.stat(filename, <span class="hljs-function"><span class="hljs-keyword">function</span> (<span class="hljs-params">err1</span>) </span>{
	<span class="hljs-keyword">var</span> err2 = <span class="hljs-keyword">new</span> VError(err1, <span class="hljs-string">'stat "%s"'</span>, filename);
	<span class="hljs-built_in">console</span>.error(err2.message);
});
</code></pre>
<p>This prints out:</p>
<pre><code>stat &quot;/nonexistent&quot;: ENOENT, stat '/nonexistent'
</code></pre>
<p>which resembles how Unix programs typically report errors:</p>
<pre><code>$ sort /nonexistent
sort: open failed: /nonexistent: No such file or directory
</code></pre>
<p>To match the Unixy feel, when you print out the error, just prepend the
program's name to the VError's <code>message</code>.  Or just call
<a href="https://github.com/joyent/node-cmdutil">node-cmdutil.fail(your_verror)</a>, which
does this for you.</p>
<p>You can get the next-level Error using <code>err.cause()</code>:</p>
<pre><code class="javascript"><span class="hljs-built_in">console</span>.error(err2.cause().message);
</code></pre>
<p>prints:</p>
<pre><code>ENOENT, stat '/nonexistent'
</code></pre>
<p>Of course, you can chain these as many times as you want, and it works with any
kind of Error:</p>
<pre><code class="javascript"><span class="hljs-keyword">var</span> err1 = <span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'No such file or directory'</span>);
<span class="hljs-keyword">var</span> err2 = <span class="hljs-keyword">new</span> VError(err1, <span class="hljs-string">'failed to stat "%s"'</span>, <span class="hljs-string">'/junk'</span>);
<span class="hljs-keyword">var</span> err3 = <span class="hljs-keyword">new</span> VError(err2, <span class="hljs-string">'request failed'</span>);
<span class="hljs-built_in">console</span>.error(err3.message);
</code></pre>
<p>This prints:</p>
<pre><code>request failed: failed to stat &quot;/junk&quot;: No such file or directory
</code></pre>
<p>The idea is that each layer in the stack annotates the error with a description
of what it was doing.  The end result is a message that explains what happened
at each level.</p>
<p>You can also decorate Error objects with additional information so that callers
can not only handle each kind of error differently, but also construct their own
error messages (e.g., to localize them, format them, group them by type, and so
on).  See the example below.</p>
<div class="pilwrap" id="deeper-dive">
  <h1>
    <a href="#deeper-dive" name="deeper-dive" class="pilcrow"></a>
Deeper dive
  </h1>
</div>
<p>The two main goals for VError are:</p>
<ul>
<li><strong>Make it easy to construct clear, complete error messages intended for
people.</strong>  Clear error messages greatly improve both user experience and
debuggability, so we wanted to make it easy to build them.  That's why the
constructor takes printf-style arguments.</li>
<li><strong>Make it easy to construct objects with programmatically-accessible
metadata</strong> (which we call <em>informational properties</em>).  Instead of just saying
&quot;connection refused while connecting to 192.168.1.2:80&quot;, you can add
properties like <code>&quot;ip&quot;: &quot;192.168.1.2&quot;</code> and <code>&quot;tcpPort&quot;: 80</code>.  This can be used
for feeding into monitoring systems, analyzing large numbers of Errors (as
from a log file), or localizing error messages.</li>
</ul>
<p>To really make this useful, it also needs to be easy to compose Errors:
higher-level code should be able to augment the Errors reported by lower-level
code to provide a more complete description of what happened.  Instead of saying
&quot;connection refused&quot;, you can say &quot;operation X failed: connection refused&quot;.
That's why VError supports <code>causes</code>.</p>
<p>In order for all this to work, programmers need to know that it's generally safe
to wrap lower-level Errors with higher-level ones.  If you have existing code
that handles Errors produced by a library, you should be able to wrap those
Errors with a VError to add information without breaking the error handling
code.  There are two obvious ways that this could break such consumers:</p>
<ul>
<li>The error's name might change.  People typically use <code>name</code> to determine what
kind of Error they've got.  To ensure compatibility, you can create VErrors
with custom names, but this approach isn't great because it prevents you from
representing complex failures.  For this reason, VError provides
<code>findCauseByName</code>, which essentially asks: does this Error <em>or any of its
causes</em> have this specific type?  If error handling code uses
<code>findCauseByName</code>, then subsystems can construct very specific causal chains
for debuggability and still let people handle simple cases easily.  There's an
example below.</li>
<li>The error's properties might change.  People often hang additional properties
off of Error objects.  If we wrap an existing Error in a new Error, those
properties would be lost unless we copied them.  But there are a variety of
both standard and non-standard Error properties that should <em>not</em> be copied in
this way: most obviously <code>name</code>, <code>message</code>, and <code>stack</code>, but also <code>fileName</code>,
<code>lineNumber</code>, and a few others.  Plus, it's useful for some Error subclasses
to have their own private properties -- and there'd be no way to know whether
these should be copied.  For these reasons, VError first-classes these
information properties.  You have to provide them in the constructor, you can
only fetch them with the <code>info()</code> function, and VError takes care of making
sure properties from causes wind up in the <code>info()</code> output.</li>
</ul>
<p>Let's put this all together with an example from the node-fast RPC library.
node-fast implements a simple RPC protocol for Node programs.  There's a server
and client interface, and clients make RPC requests to servers.  Let's say the
server fails with an UnauthorizedError with message &quot;user 'bob' is not
authorized&quot;.  The client wraps all server errors with a FastServerError.  The
client also wraps all request errors with a FastRequestError that includes the
name of the RPC call being made.  The result of this failed RPC might look like
this:</p>
<pre><code>name: FastRequestError
message: &quot;request failed: server error: user 'bob' is not authorized&quot;
rpcMsgid: &lt;unique identifier for this request&gt;
rpcMethod: GetObject
cause:
    name: FastServerError
    message: &quot;server error: user 'bob' is not authorized&quot;
    cause:
        name: UnauthorizedError
        message: &quot;user 'bob' is not authorized&quot;
        rpcUser: &quot;bob&quot;
</code></pre>
<p>When the caller uses <code>VError.info()</code>, the information properties are collapsed
so that it looks like this:</p>
<pre><code>message: &quot;request failed: server error: user 'bob' is not authorized&quot;
rpcMsgid: &lt;unique identifier for this request&gt;
rpcMethod: GetObject
rpcUser: &quot;bob&quot;
</code></pre>
<p>Taking this apart:</p>
<ul>
<li>The error's message is a complete description of the problem.  The caller can
report this directly to its caller, which can potentially make its way back to
an end user (if appropriate).  It can also be logged.</li>
<li>The caller can tell that the request failed on the server, rather than as a
result of a client problem (e.g., failure to serialize the request), a
transport problem (e.g., failure to connect to the server), or something else
(e.g., a timeout).  They do this using <code>findCauseByName('FastServerError')</code>
rather than checking the <code>name</code> field directly.</li>
<li>If the caller logs this error, the logs can be analyzed to aggregate
errors by cause, by RPC method name, by user, or whatever.  Or the
error can be correlated with other events for the same rpcMsgid.</li>
<li>It wasn't very hard for any part of the code to contribute to this Error.
Each part of the stack has just a few lines to provide exactly what it knows,
with very little boilerplate.</li>
</ul>
<p>It's not expected that you'd use these complex forms all the time.  Despite
supporting the complex case above, you can still just do:</p>
<p>new VError(&quot;my service isn't working&quot;);</p>
<p>for the simple cases.</p>
<div class="pilwrap" id="reference-verror-werror-serror">
  <h1>
    <a href="#reference-verror-werror-serror" name="reference-verror-werror-serror" class="pilcrow"></a>
Reference: VError, WError, SError
  </h1>
</div>
<p>VError, WError, and SError are convenient drop-in replacements for <code>Error</code> that
support printf-style arguments, first-class causes, informational properties,
and other useful features.</p>
<div class="pilwrap" id="constructors">
  <h2>
    <a href="#constructors" name="constructors" class="pilcrow"></a>
Constructors
  </h2>
</div>
<p>The VError constructor has several forms:</p>
<pre><code class="javascript"><span class="hljs-comment">/*
 * This is the most general form.  You can specify any supported options
 * (including "cause" and "info") this way.
 */</span>
<span class="hljs-keyword">new</span> VError(options, sprintf_args...)

<span class="hljs-comment">/*
 * This is a useful shorthand when the only option you need is "cause".
 */</span>
<span class="hljs-keyword">new</span> VError(cause, sprintf_args...)

<span class="hljs-comment">/*
 * This is a useful shorthand when you don't need any options at all.
 */</span>
<span class="hljs-keyword">new</span> VError(sprintf_args...)
</code></pre>
<p>All of these forms construct a new VError that behaves just like the built-in
JavaScript <code>Error</code> class, with some additional methods described below.</p>
<p>In the first form, <code>options</code> is a plain object with any of the following
optional properties:</p>
<table>
<thead>
<tr>
<th>Option name</th>
<th>Type</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>name</code></td>
<td>string</td>
<td>Describes what kind of error this is.  This is intended for programmatic use to distinguish between different kinds of errors.  Note that in modern versions of Node.js, this name is ignored in the <code>stack</code> property value, but callers can still use the <code>name</code> property to get at it.</td>
</tr>
<tr>
<td><code>cause</code></td>
<td>any Error object</td>
<td>Indicates that the new error was caused by <code>cause</code>.  See <code>cause()</code> below.  If unspecified, the cause will be <code>null</code>.</td>
</tr>
<tr>
<td><code>strict</code></td>
<td>boolean</td>
<td>If true, then <code>null</code> and <code>undefined</code> values in <code>sprintf_args</code> are passed through to <code>sprintf()</code>.  Otherwise, these are replaced with the strings <code>'null'</code>, and '<code>undefined</code>', respectively.</td>
</tr>
<tr>
<td><code>constructorOpt</code></td>
<td>function</td>
<td>If specified, then the stack trace for this error ends at function <code>constructorOpt</code>.  Functions called by <code>constructorOpt</code> will not show up in the stack.  This is useful when this class is subclassed.</td>
</tr>
<tr>
<td><code>info</code></td>
<td>object</td>
<td>Specifies arbitrary informational properties that are available through the <code>VError.info(err)</code> static class method.  See that method for details.</td>
</tr>
</tbody>
</table>
<p>The second form is equivalent to using the first form with the specified <code>cause</code>
as the error's cause.  This form is distinguished from the first form because
the first argument is an Error.</p>
<p>The third form is equivalent to using the first form with all default option
values.  This form is distinguished from the other forms because the first
argument is not an object or an Error.</p>
<p>The <code>WError</code> constructor is used exactly the same way as the <code>VError</code>
constructor.  The <code>SError</code> constructor is also used the same way as the
<code>VError</code> constructor except that in all cases, the <code>strict</code> property is
overriden to `true.</p>
<div class="pilwrap" id="public-properties">
  <h2>
    <a href="#public-properties" name="public-properties" class="pilcrow"></a>
Public properties
  </h2>
</div>
<p><code>VError</code>, <code>WError</code>, and <code>SError</code> all provide the same public properties as
JavaScript's built-in Error objects.</p>
<table>
<thead>
<tr>
<th>Property name</th>
<th>Type</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>name</code></td>
<td>string</td>
<td>Programmatically-usable name of the error.</td>
</tr>
<tr>
<td><code>message</code></td>
<td>string</td>
<td>Human-readable summary of the failure.  Programmatically-accessible details are provided through <code>VError.info(err)</code> class method.</td>
</tr>
<tr>
<td><code>stack</code></td>
<td>string</td>
<td>Human-readable stack trace where the Error was constructed.</td>
</tr>
</tbody>
</table>
<p>For all of these classes, the printf-style arguments passed to the constructor
are processed with <code>sprintf()</code> to form a message.  For <code>WError</code>, this becomes
the complete <code>message</code> property.  For <code>SError</code> and <code>VError</code>, this message is
prepended to the message of the cause, if any (with a suitable separator), and
the result becomes the <code>message</code> property.</p>
<p>The <code>stack</code> property is managed entirely by the underlying JavaScript
implementation.  It's generally implemented using a getter function because
constructing the human-readable stack trace is somewhat expensive.</p>
<div class="pilwrap" id="class-methods">
  <h2>
    <a href="#class-methods" name="class-methods" class="pilcrow"></a>
Class methods
  </h2>
</div>
<p>The following methods are defined on the <code>VError</code> class and as exported
functions on the <code>verror</code> module.  They're defined this way rather than using
methods on VError instances so that they can be used on Errors not created with
<code>VError</code>.</p>
<div class="pilwrap" id="verror.cause-err">
  <h3>
    <a href="#verror.cause-err" name="verror.cause-err" class="pilcrow"></a>
<code>VError.cause(err)</code>
  </h3>
</div>
<p>The <code>cause()</code> function returns the next Error in the cause chain for <code>err</code>, or
<code>null</code> if there is no next error.  See the <code>cause</code> argument to the constructor.
Errors can have arbitrarily long cause chains.  You can walk the <code>cause</code> chain
by invoking <code>VError.cause(err)</code> on each subsequent return value.  If <code>err</code> is
not a <code>VError</code>, the cause is <code>null</code>.</p>
<div class="pilwrap" id="verror.info-err">
  <h3>
    <a href="#verror.info-err" name="verror.info-err" class="pilcrow"></a>
<code>VError.info(err)</code>
  </h3>
</div>
<p>Returns an object with all of the extra error information that's been associated
with this Error and all of its causes.  These are the properties passed in using
the <code>info</code> option to the constructor.  Properties not specified in the
constructor for this Error are implicitly inherited from this error's cause.</p>
<p>These properties are intended to provide programmatically-accessible metadata
about the error.  For an error that indicates a failure to resolve a DNS name,
informational properties might include the DNS name to be resolved, or even the
list of resolvers used to resolve it.  The values of these properties should
generally be plain objects (i.e., consisting only of null, undefined, numbers,
booleans, strings, and objects and arrays containing only other plain objects).</p>
<div class="pilwrap" id="verror.fullstack-err">
  <h3>
    <a href="#verror.fullstack-err" name="verror.fullstack-err" class="pilcrow"></a>
<code>VError.fullStack(err)</code>
  </h3>
</div>
<p>Returns a string containing the full stack trace, with all nested errors recursively
reported as <code>'caused by:' + err.stack</code>.</p>
<div class="pilwrap" id="verror.findcausebyname-err-name">
  <h3>
    <a href="#verror.findcausebyname-err-name" name="verror.findcausebyname-err-name" class="pilcrow"></a>
<code>VError.findCauseByName(err, name)</code>
  </h3>
</div>
<p>The <code>findCauseByName()</code> function traverses the cause chain for <code>err</code>, looking
for an error whose <code>name</code> property matches the passed in <code>name</code> value. If no
match is found, <code>null</code> is returned.</p>
<p>If all you want is to know <em>whether</em> there's a cause (and you don't care what it
is), you can use <code>VError.hasCauseWithName(err, name)</code>.</p>
<p>If a vanilla error or a non-VError error is passed in, then there is no cause
chain to traverse. In this scenario, the function will check the <code>name</code>
property of only <code>err</code>.</p>
<div class="pilwrap" id="verror.hascausewithname-err-name">
  <h3>
    <a href="#verror.hascausewithname-err-name" name="verror.hascausewithname-err-name" class="pilcrow"></a>
<code>VError.hasCauseWithName(err, name)</code>
  </h3>
</div>
<p>Returns true if and only if <code>VError.findCauseByName(err, name)</code> would return
a non-null value.  This essentially determines whether <code>err</code> has any cause in
its cause chain that has name <code>name</code>.</p>
<div class="pilwrap" id="verror.errorfromlist-errors">
  <h3>
    <a href="#verror.errorfromlist-errors" name="verror.errorfromlist-errors" class="pilcrow"></a>
<code>VError.errorFromList(errors)</code>
  </h3>
</div>
<p>Given an array of Error objects (possibly empty), return a single error
representing the whole collection of errors.  If the list has:</p>
<ul>
<li>0 elements, returns <code>null</code></li>
<li>1 element, returns the sole error</li>
<li>more than 1 element, returns a MultiError referencing the whole list</li>
</ul>
<p>This is useful for cases where an operation may produce any number of errors,
and you ultimately want to implement the usual <code>callback(err)</code> pattern.  You can
accumulate the errors in an array and then invoke
<code>callback(VError.errorFromList(errors))</code> when the operation is complete.</p>
<div class="pilwrap" id="verror.errorforeach-err-func">
  <h3>
    <a href="#verror.errorforeach-err-func" name="verror.errorforeach-err-func" class="pilcrow"></a>
<code>VError.errorForEach(err, func)</code>
  </h3>
</div>
<p>Convenience function for iterating an error that may itself be a MultiError.</p>
<p>In all cases, <code>err</code> must be an Error.  If <code>err</code> is a MultiError, then <code>func</code> is
invoked as <code>func(errorN)</code> for each of the underlying errors of the MultiError.
If <code>err</code> is any other kind of error, <code>func</code> is invoked once as <code>func(err)</code>.  In
all cases, <code>func</code> is invoked synchronously.</p>
<p>This is useful for cases where an operation may produce any number of warnings
that may be encapsulated with a MultiError -- but may not be.</p>
<p>This function does not iterate an error's cause chain.</p>
<div class="pilwrap" id="examples">
  <h2>
    <a href="#examples" name="examples" class="pilcrow"></a>
Examples
  </h2>
</div>
<p>The &quot;Demo&quot; section above covers several basic cases.  Here's a more advanced
case:</p>
<pre><code class="javascript"><span class="hljs-keyword">var</span> err1 = <span class="hljs-keyword">new</span> VError(<span class="hljs-string">'something bad happened'</span>);
<span class="hljs-comment">/* ... */</span>
<span class="hljs-keyword">var</span> err2 = <span class="hljs-keyword">new</span> VError({
    <span class="hljs-string">'name'</span>: <span class="hljs-string">'ConnectionError'</span>,
    <span class="hljs-string">'cause'</span>: err1,
    <span class="hljs-string">'info'</span>: {
        <span class="hljs-string">'errno'</span>: <span class="hljs-string">'ECONNREFUSED'</span>,
        <span class="hljs-string">'remote_ip'</span>: <span class="hljs-string">'127.0.0.1'</span>,
        <span class="hljs-string">'port'</span>: <span class="hljs-number">215</span>
    }
}, <span class="hljs-string">'failed to connect to "%s:%d"'</span>, <span class="hljs-string">'127.0.0.1'</span>, <span class="hljs-number">215</span>);

<span class="hljs-built_in">console</span>.log(err2.message);
<span class="hljs-built_in">console</span>.log(err2.name);
<span class="hljs-built_in">console</span>.log(VError.info(err2));
<span class="hljs-built_in">console</span>.log(err2.stack);
</code></pre>
<p>This outputs:</p>
<pre><code>failed to connect to &quot;127.0.0.1:215&quot;: something bad happened
ConnectionError
{ errno: 'ECONNREFUSED', remote_ip: '127.0.0.1', port: 215 }
ConnectionError: failed to connect to &quot;127.0.0.1:215&quot;: something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/info.js:5:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
</code></pre>
<p>Information properties are inherited up the cause chain, with values at the top
of the chain overriding same-named values lower in the chain.  To continue that
example:</p>
<pre><code class="javascript"><span class="hljs-keyword">var</span> err3 = <span class="hljs-keyword">new</span> VError({
    <span class="hljs-string">'name'</span>: <span class="hljs-string">'RequestError'</span>,
    <span class="hljs-string">'cause'</span>: err2,
    <span class="hljs-string">'info'</span>: {
        <span class="hljs-string">'errno'</span>: <span class="hljs-string">'EBADREQUEST'</span>
    }
}, <span class="hljs-string">'request failed'</span>);

<span class="hljs-built_in">console</span>.log(err3.message);
<span class="hljs-built_in">console</span>.log(err3.name);
<span class="hljs-built_in">console</span>.log(VError.info(err3));
<span class="hljs-built_in">console</span>.log(err3.stack);
</code></pre>
<p>This outputs:</p>
<pre><code>request failed: failed to connect to &quot;127.0.0.1:215&quot;: something bad happened
RequestError
{ errno: 'EBADREQUEST', remote_ip: '127.0.0.1', port: 215 }
RequestError: request failed: failed to connect to &quot;127.0.0.1:215&quot;: something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/info.js:20:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
</code></pre>
<p>You can also print the complete stack trace of combined <code>Error</code>s by using
<code>VError.fullStack(err).</code></p>
<pre><code class="javascript"><span class="hljs-keyword">var</span> err1 = <span class="hljs-keyword">new</span> VError(<span class="hljs-string">'something bad happened'</span>);
<span class="hljs-comment">/* ... */</span>
<span class="hljs-keyword">var</span> err2 = <span class="hljs-keyword">new</span> VError(err1, <span class="hljs-string">'something really bad happened here'</span>);

<span class="hljs-built_in">console</span>.log(VError.fullStack(err2));
</code></pre>
<p>This outputs:</p>
<pre><code>VError: something really bad happened here: something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/fullStack.js:5:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
caused by: VError: something bad happened
    at Object.&lt;anonymous&gt; (/home/dap/node-verror/examples/fullStack.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
</code></pre>
<p><code>VError.fullStack</code> is also safe to use on regular <code>Error</code>s, so feel free to use
it whenever you need to extract the stack trace from an <code>Error</code>, regardless if
it's a <code>VError</code> or not.</p>
<div class="pilwrap" id="reference-multierror">
  <h1>
    <a href="#reference-multierror" name="reference-multierror" class="pilcrow"></a>
Reference: MultiError
  </h1>
</div>
<p>MultiError is an Error class that represents a group of Errors.  This is used
when you logically need to provide a single Error, but you want to preserve
information about multiple underying Errors.  A common case is when you execute
several operations in parallel and some of them fail.</p>
<p>MultiErrors are constructed as:</p>
<pre><code class="javascript"><span class="hljs-keyword">new</span> MultiError(error_list)
</code></pre>
<p><code>error_list</code> is an array of at least one <code>Error</code> object.</p>
<p>The cause of the MultiError is the first error provided.  None of the other
<code>VError</code> options are supported.  The <code>message</code> for a MultiError consists the
<code>message</code> from the first error, prepended with a message indicating that there
were other errors.</p>
<p>For example:</p>
<pre><code class="javascript">err = <span class="hljs-keyword">new</span> MultiError([
    <span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'failed to resolve DNS name "abc.example.com"'</span>),
    <span class="hljs-keyword">new</span> <span class="hljs-built_in">Error</span>(<span class="hljs-string">'failed to resolve DNS name "def.example.com"'</span>),
]);

<span class="hljs-built_in">console</span>.error(err.message);
</code></pre>
<p>outputs:</p>
<pre><code>first of 2 errors: failed to resolve DNS name &quot;abc.example.com&quot;
</code></pre>
<p>See the convenience function <code>VError.errorFromList</code>, which is sometimes simpler
to use than this constructor.</p>
<div class="pilwrap" id="public-methods">
  <h2>
    <a href="#public-methods" name="public-methods" class="pilcrow"></a>
Public methods
  </h2>
</div>
<div class="pilwrap" id="errors">
  <h3>
    <a href="#errors" name="errors" class="pilcrow"></a>
<code>errors()</code>
  </h3>
</div>
<p>Returns an array of the errors used to construct this MultiError.</p>
<div class="pilwrap" id="contributing">
  <h1>
    <a href="#contributing" name="contributing" class="pilcrow"></a>
Contributing
  </h1>
</div>
<p>See separate <a href="CONTRIBUTING.md.html">contribution guidelines</a>.</p>
</div>
  </div>
</body>
</html>
